apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: my_app_replicaset
 labels:
  app: my_app
  type: front_end
spec:
 template:
  metadata:
   name: nginx-2   #pod_name
   labels:
  env: production
  spec:
  containers:
   - name: nginx-2
     image: nginx 
replicas: 3
selector:
 matchLabels:
  type: front_end